import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { NavBar } from '@/components/navbar';
import { Footer } from '@/components/footer';

const roboto = Roboto ({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>
        <NavBar/>
        {children} 
        <Footer/>     
      </body>
    </html>
  )
}
